add ret2, ret3 to 8.2 benchmark
ret1 listed but ret2, ret3 referenced. Resolves:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1071, in _thread_return
        return_data = func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/cis.py", line 2549, in audit_8_2
        if not (ret1 or ret2 or ret3):
    NameError: global name 'ret2' is not defined